from typing import Union, List, Dict, Any
from typing_extensions import TypedDict


class BaseConfig(TypedDict):
    RETRIEVER: str
    EMBEDDING: str
    SIMILARITY_THRESHOLD: float
    FAST_LLM: str
    SMART_LLM: str
    STRATEGIC_LLM: str
    FAST_TOKEN_LIMIT: int
    SMART_TOKEN_LIMIT: int
    STRATEGIC_TOKEN_LIMIT: int
    BROWSE_CHUNK_MAX_LENGTH: int
    SUMMARY_TOKEN_LIMIT: int
    TEMPERATURE: float
    USER_AGENT: str
    MAX_SEARCH_RESULTS_PER_QUERY: int
    PLANNING_EVIDENCE_ENABLED: bool
    PLANNING_SEARCH_RESULTS: int
    PRE_SCRAPE_SOURCE_CURATION: bool
    PRE_SCRAPE_MAX_SOURCES_PER_QUERY: int
    POST_SCRAPE_SOURCE_INTEGRITY: bool
    SOURCE_CURATION_POLICY: str
    RETRIEVAL_PIPELINE_MODE: str
    SOURCE_EVIDENCE_JUDGE_MODE: str
    SOURCE_EVIDENCE_JUDGE_FALLBACK: str
    CANONICAL_CONTENT_RESOLUTION: bool
    MEMORY_BACKEND: str
    TOTAL_WORDS: int
    REPORT_FORMAT: str
    CURATE_SOURCES: bool
    MAX_ITERATIONS: int
    LANGUAGE: str
    AGENT_ROLE: Union[str, None]
    SCRAPER: str
    MAX_SCRAPER_WORKERS: int
    SCRAPER_RATE_LIMIT_DELAY: float
    MAX_SUBTOPICS: int
    REPORT_SOURCE: Union[str, None]
    DOC_PATH: str
    PROMPT_FAMILY: str
    LLM_KWARGS: dict
    EMBEDDING_KWARGS: dict
    VERBOSE: bool
    DEEP_RESEARCH_CONCURRENCY: int
    DEEP_RESEARCH_DEPTH: int
    DEEP_RESEARCH_BREADTH: int
    DEEP_RESEARCH_FOCUSED_RETRIEVAL: bool
    DEEP_RESEARCH_TREE_POLICY: str
    DEEP_RESEARCH_BRANCH_MODE: str
    DEEP_RESEARCH_MAX_DEEPENED_BRANCHES: int
    DEEP_RESEARCH_MIN_DEEPENING_SCORE: int
    DEEP_RESEARCH_SOURCE_STANDARDS: bool
    DEEP_RESEARCH_DIRECT_URL_SEED: bool
    SOURCE_SELECTOR_MODE: str
    RESEARCH_TRAJECTORY_ENABLED: bool
    RESEARCH_TRAJECTORY_DIR: str
    RESEARCH_DURATION_CONTROLLER_MODE: str
    RESEARCH_DURATION_DEFAULT_SECONDS: int
    RESEARCH_DURATION_MIN_SECONDS: int
    RESEARCH_DURATION_MAX_SECONDS: int
    RESEARCH_BUDGET_CALIBRATION_ENABLED: bool
    RESEARCH_BUDGET_CALIBRATION_MIN_SAMPLES: int
    DEEP_RESEARCH_PDF_CONNECT_TIMEOUT_SECONDS: float
    DEEP_RESEARCH_PDF_TOTAL_TIMEOUT_SECONDS: float
    DEEP_RESEARCH_PDF_MAX_BYTES: int
    DEEP_RESEARCH_ADAPTIVE_COMPRESSION: bool
    DEEP_RESEARCH_SIMILARITY_RESCUE_FLOOR: float
    DEEP_RESEARCH_MAX_CONTEXT_CHUNKS: int
    DEEP_RESEARCH_MAX_CHUNKS_PER_SOURCE: int
    DEEP_RESEARCH_FALLBACK_CORROBORATION_ENABLED: bool
    DEEP_RESEARCH_FALLBACK_CORROBORATION: int
    MCP_SERVERS: List[Dict[str, Any]]
    MCP_AUTO_TOOL_SELECTION: bool
    MCP_USE_LLM_ARGS: bool
    MCP_ALLOWED_ROOT_PATHS: List[str]
    MCP_STRATEGY: str
    REASONING_EFFORT: str
    # Image generation settings
    IMAGE_GENERATION_MODEL: Union[str, None]
    IMAGE_GENERATION_MAX_IMAGES: int
    IMAGE_GENERATION_ENABLED: bool
    IMAGE_GENERATION_STYLE: str  # Image style: "dark", "light", or "auto"
    IMAGE_GENERATION_PROVIDER: str  # Image provider: "google" or "modelslab"
    LLAMA_SWAP_URL: str
    LLAMA_SWAP_ENABLED: bool
    LLAMA_SWAP_TIMEOUT: float
